# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.guanqiaofeng@gmail.com
author_full_name: Guanqiao Feng
github_username: guanqiaofeng
has_additional_authors: false
project_description: UHN Breast Xevaset V2025 is a curation pipeline that curate all
    PDX data generated in Cescon lab by 2025
project_name: UHN Breast Xevaset V2025
project_slug: uhn-breast-xevaset-v2025
publish_to_github: true
python_version: '3.12'
repo_location: guanqiaofeng
